# Generated by Django 5.2.5 on 2025-08-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='accounts.course'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'course')},
        ),
    ]
